### PR TITLE
Fix inconsistency between binary and ASCII protocols

### LINKED ISSUE #75: Inconsistency between Binary and ASCII protocols
When using binary protocol, `add`ing a key when it already exists results in `Err(MemcacheError::ServerError(0x02))` (`ResponseStatus::KeyExists` error) but with ASCII protocol, the library returns `Ok(())`. Issue is [here](https://github.com/aisk/rust-memcache/blob/66bd9671df31377f3edf9e4fce7d7aa11615d23f/src/protocol/ascii.rs#L83)

### PR DESCRIPTION
**Pull request by letmutx**
FIxes #75

### CODE REVIEW

File: src/protocol/ascii.rs [hunk 1]
```diff
@@ -95,8 +96,10 @@ impl AsciiProtocol<Stream> {
             return Ok(true);
         } else if s == "NOT_STORED\r\n" {
             return Ok(false);
-        } else if command == StoreCommand::Cas && (s == "EXISTS\r\n" || s == "NOT_FOUND\r\n") {
-            return Ok(false);
+        } else if s == "EXISTS\r\n" {
+            return Err(MemcacheError::from(ResponseStatus::KeyExists as u16));
```
Comment (aisk) [inline src/protocol/ascii.rs]: Now the binary protocol and ascii protocol do not using a unified error system, I think it should be a issue, and we should resolve it in the future, with some predefined error like `KeyExists` / `KeyNotFound`.

But for now, I think we should keep the ascii protocol using the old (and ugly)  string based error.

Comment (letmutx) [reply src/protocol/ascii.rs]: Didn't get what you're trying to say. We're returning the same error in binary protocol.

Comment (aisk) [reply src/protocol/ascii.rs]: Just took another look, I thought we should refactor the whole error system, but for now I think it's ok. merging.
